name: wethepeople
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  audio_service: ^0.18.3
  audioplayers: ^0.20.1
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.4
  firebase_core: ^1.12.0
  firebase_messaging: ^11.2.6
  flutter:
    sdk: flutter
  flutter_neumorphic: ^3.2.0
#  google_fonts: ^2.2.0
  http: ^0.13.4
  # media_notification: ^0.0.1
  music_visualizer: ^1.0.2
  url_launcher: ^6.0.18
  flutter_media_notification: ^1.2.6
  whatsapp_unilink: ^2.0.1+1

dev_dependencies:
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/logo_1024_wht.png"

flutter:

  uses-material-design: true
  assets:
    - assets/images/
